package lint

const SUCCESS = 0
const LINT_ERROR = 1
const FILE_OR_FOLDER_NOT_FOUND = 2
const INVALID_FILE_FORMAT = 3
const INVALID_TFVARS_SYNTAX = 4
const INVALID_VARIABLE_FILE_SYNTAX = 5
const NO_TFVARS_FOUND = 6
const NO_VARIABLE_FILES_FOUND = 7
